### ISSUE TITLE
[feature] Display info regarding new available version when used with -y flag

### ISSUE THREAD

**Issue by Celleb** [johndcarmichael/boats#27]
Currently, the `-y` stops the version check, but I will be nice if it will check and just display a new version message without stopping the build, and possibly a link to the release notes. In this case, I'll know there's a new version and I'll update when I see fit. @p-mcgowan

**Comment by Acrontum-Carmichael** [comment]
@p-mcgowan  i think you left out the version check as it messed with a CI pipe right?

**Comment by Acrontum-Carmichael** [comment]
the npm version checker could easily be extended - might be a simpler solution.. open to changing it

**Comment by p-mcgowan** [comment]
I don't think the CI pipe was an issue - that we could use the new `--yes` flag for.

I initially hardcoded in `if (process.env.NODE_ENV === 'test') { <skip thinger> }` because it messed with running tests. It makes sense (in my mind at least) that in test env, it should not check for updates, and when not in test env, you can disable the complaining by `--yes`'ing it out. I think that should cover the use cases

**Comment by p-mcgowan** [comment]
close in https://github.com/johndcarmichael/boats/pull/28
